(*************************************************************************)
(* This file contains a set of examples to generate a LEAN4 file         *)
(*************************************************************************)

open Lean_ast
open Lean_printer

let example1 : lean_file = {
  header  = Some "LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR PROOF OBLIGATIONS";
  imports = [
    Import "LeanVeri.LinearMapPropositions";
    Import "LeanVeri.Commons";
  ];
  declarations = [
    Variable [
      { name = "𝕜"; type_b = Type };
      { name = "_inst"; type_b = app (v "RCLike") (v "𝕜") }
    ];
    Notation {
      is_local    = true;
      symbol      = "𝕜²";
      definition  = 
        app (app (v "EuclideanSpace") (v "𝕜")) (app (v "Fin") (LitInt 2))
    };
    Lemma {
      name    = "obligation1";
      params  = [];
      type_b  = BinOp (
        "=",
        BinOp ("+", v "ketbra0", v "ketbra1"),
        Annotation (
          LitInt 1,
          GenericRepr "𝕜² →ₗ[𝕜] 𝕜²"
        )
      );
      body = Sorry;
    }
  ];
}

let () = 
  let output = lean_ast_to_lean_file example1
  print_endline output