/- LEAN4 FILE AUTO GENERATED BY CQOTL PROVER FOR OBLIGATION: obligation_11 -/

import LeanVeri.Commons
import LeanVeri.LinearMapPropositions
import LeanVeri.ProjectionSubmodule

variable {𝕜 : Type*} [_inst : (RCLike 𝕜)]

local notation "𝕜²" => ((EuclideanSpace 𝕜) (Fin 2))

<<<<<<< HEAD:lean-veri/LeanVeri/Examples/obligation_11.lean
def iadd  : (ℤ → (Bool → ℤ)) := sorry

def lt  : (ℤ → (ℤ → Bool)) := sorry
=======
def lt : (ℤ → (ℤ → Bool)) := fun x y ↦ x < y
>>>>>>> 71997f0e07c6aed2287af76a5961d81bcbacc242:lean-veri/LeanVeri/Proofs/Example1/obligation_11.lean

/- This seems to be false -/
lemma obligation_11 (x' : ℤ) (x : ℤ) (i' : ℤ) (i : ℤ) (m : ℤ) :
<<<<<<< HEAD:lean-veri/LeanVeri/Examples/obligation_11.lean
 ∀ (H0 : ((¬ ((((lt ((iadd i) true)) m) = ((lt ((iadd i') true)) m)) ∧ ((x = x') ∧ (((iadd i) true) = ((iadd i') true))))) = true)), ((¬ ((((lt i) m) = ((lt i') m)) ∧ ((x = x') ∧ (i = i')))) = true) := sorry
=======
    ((¬ ((((lt i) m) = ((lt i') m)) ∧ ((x = x') ∧ (i = i')))) = true) := by
  sorry
  
>>>>>>> 71997f0e07c6aed2287af76a5961d81bcbacc242:lean-veri/LeanVeri/Proofs/Example1/obligation_11.lean
